### ISSUE TITLE
Cannot read property 'technique0' of undefined

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#11]
I tried the latest version library and it got an error.

https://unpkg.com/grimoirejs-preset-basic@1.9.22/register/grimoire-preset-basic.js
https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js

Model : http://jsrun.it/assets/G/s/5/8/Gs58O (glTF-Embedded/Duck.gltf)
See: http://jsdo.it/cx20/irCY (http://jsrun.it/cx20/irCY)
```
Uncaught (in promise) TypeError: Cannot read property 'technique0' of undefined
    at Function._callee$ (https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js:1001:82)
    at tryCatch (https://unpkg.com/grimoirejs-preset-basic@1.9.22/register/grimoire-preset-basic.js:34297:40)
    at Generator.invoke [as _invoke] (https://unpkg.com/grimoirejs-preset-basic@1.9.22/register/grimoire-preset-basic.js:34532:22)
    at Generator.prototype.(anonymous function) [as next] (https://unpkg.com/grimoirejs-preset-basic@1.9.22/register/grimoire-preset-basic.js:34349:21)
    at https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js:973:71
    at Promise (<anonymous>)
    at __awaiter (https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js:953:12)
    at Function.parse (https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js:985:20)
    at Function._callee$ (https://unpkg.com/grimoirejs-gltf@1.8.9/register/grimoire-gltf.js:1446:65)
    at tryCatch (https://unpkg.com/grimoirejs-preset-basic@1.9.22/register/grimoire-preset-basic.js:34297:40)
```

**Comment by kyasbal-1994** [comment]
Fixed by https://github.com/GrimoireGL/grimoirejs-gltf/releases/tag/v1.8.10
