### ISSUE TITLE
Failed to load glTF model without NORMAL or TEXCOORD_0

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#20]
I failed to load the following model.

Model : Triangle
https://github.com/cx20/gltf-test/tree/2.0/tutorialModels/Triangle

Result :
https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/grimoiregl/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF
```
Uncaught Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RendererComponent.$renderViewport
error:Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RenderSceneComponent.$render
error:Error: Specified buffer "NORMAL was not found on this geometry while attempt to bind "normal" of attribute variables.

      All of the vertex buffer available on this geometry is POSITION"
Error: Specified buffer "NORMAL was not found on this geometry while attempt to bind "normal" of attribute variables.

      All of the vertex buffer available on this geometry is POSITION"
    at Function.bindBufferToAttribute (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9728:23)
    at Pass.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16129:36)
    at Technique.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16391:32)
    at Material.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:10777:27)
    at MeshRenderer.render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:13229:46)
    at https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17386:30
    at Array.forEach (native)
    at RenderQueue.renderAll (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17385:30)
    at CameraComponent.renderScene (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:11723:35)
    at RenderSceneComponent.$render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9289:20)

)
Error: Uncaught, unspecified "error" event. (
```

**Comment by cx20** [comment]
TEXCOORD also has the same problem.

Model : Box
https://github.com/cx20/gltf-test/tree/2.0/sampleModels/Box

Result :
https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/grimoiregl/index.html?category=sampleModels&model=Box&scale=1&type=glTF
```
Uncaught Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RendererComponent.$renderViewport
error:Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RenderSceneComponent.$render
error:Error: Specified buffer "TEXCOORD_0 was not found on this geometry while attempt to bind "texCoord" of attribute variables.

      All of the vertex buffer available on this geometry is NORMAL,POSITION"
Error: Specified buffer "TEXCOORD_0 was not found on this geometry while attempt to bind "texCoord" of attribute variables.

      All of the vertex buffer available on this geometry is NORMAL,POSITION"
    at Function.bindBufferToAttribute (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9728:23)
    at Pass.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16129:36)
    at Technique.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16391:32)
    at Material.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:10777:27)
    at MeshRenderer.render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:13229:46)
    at https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17386:30
    at Array.forEach (native)
    at RenderQueue.renderAll (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17385:30)
    at CameraComponent.renderScene (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:11723:35)
    at RenderSceneComponent.$render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9289:20)

)
Error: Uncaught, unspecified "error" event. (

```

**Comment by cx20** [comment]
I confirmed that the model is displayed correctly.

[Triangle Result](https://cdn.rawgit.com/cx20/gltf-test/6d7b1f4a887b9fbae98e6c4823e8f20c0dd91948/examples/grimoiregl/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF)
![image](https://cloud.githubusercontent.com/assets/1833979/26284233/8a19c30a-3e71-11e7-8a5e-28cc93a9e31b.png)

[Box Result](https://cdn.rawgit.com/cx20/gltf-test/6d7b1f4a887b9fbae98e6c4823e8f20c0dd91948/examples/grimoiregl/index.html?model=BoxWithoutIndices&scale=1)
![image](https://cloud.githubusercontent.com/assets/1833979/26284245/aaff6494-3e71-11e7-8067-360f965b8745.png)
