### ISSUE TITLE
The morphing glTF model is not displayed

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#25]
I failed to load the following model. It is probably because the loader does not support the morphing glTF model yet.

Model : Animated Morph Cube
https://github.com/cx20/gltf-test/tree/2.0/tutorialModels/AnimatedMorphCube

Result :
https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/grimoiregl/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF
```
Uncaught Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RendererComponent.$renderViewport
error:Error: Uncaught, unspecified "error" event. (

[MESSAGE STACK] at RenderSceneComponent.$render
error:Error: Specified buffer "TEXCOORD_0 was not found on this geometry while attempt to bind "texCoord" of attribute variables.

      All of the vertex buffer available on this geometry is NORMAL,TANGENT,POSITION"
Error: Specified buffer "TEXCOORD_0 was not found on this geometry while attempt to bind "texCoord" of attribute variables.

      All of the vertex buffer available on this geometry is NORMAL,TANGENT,POSITION"
    at Function.bindBufferToAttribute (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9728:23)
    at Pass.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16129:36)
    at Technique.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:16391:32)
    at Material.draw (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:10777:27)
    at MeshRenderer.render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:13229:46)
    at https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17386:30
    at Array.forEach (native)
    at RenderQueue.renderAll (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:17385:30)
    at CameraComponent.renderScene (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:11723:35)
    at RenderSceneComponent.$render (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/grimoiregl/grimoirejs-preset-basic/1.9.28/grimoire-preset-basic.js:9289:20)

)
Error: Uncaught, unspecified "error" event. (
```

Relate : https://github.com/GrimoireGL/grimoirejs-gltf/issues/20

**Comment by kyasbal-1994** [comment]
Confirmed this problem was fiexed until last commit 61d756.

**Comment by cx20** [comment]
I confirmed that the cube will be displayed with the latest version.
![image](https://cloud.githubusercontent.com/assets/1833979/26590253/020a5a58-4595-11e7-89df-4f4100434f7e.png)

I will report morphing is not done as a separate issue.
