### ISSUE TITLE
Does not support glTF binary format

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#4]
https://cx20.github.io/gltf-test/

If you try to display the Box model of glTF-Binary format in Grimoire.js, an error will be displayed on the console.

https://cx20.github.io/gltf-test/examples/grimoiregl/index.html?category=sampleModels&model=Box&scale=1&type=glTF-Binary
```
grimoire-gltf.min.js:1
Uncaught (in promise) SyntaxError: Unexpected token g in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (https://cx20.github.io/gltf-test/libs/grimoiregl/grimoirejs-gltf/1.7.1/grimoire-gltf.min.js:1:17959)
    at tryCatch (https://cx20.github.io/gltf-test/libs/grimoiregl/grimoirejs-preset-basic/1.6.6/grimoire-preset-basic.js:7361:41)
    at Generator.invoke [as _invoke] (https://cx20.github.io/gltf-test/libs/grimoiregl/grimoirejs-preset-basic/1.6.6/grimoire-preset-basic.js:7652:23)
    at Generator.prototype.(anonymous function) [as next] (https://cx20.github.io/gltf-test/libs/grimoiregl/grimoirejs-preset-basic/1.6.6/grimoire-preset-basic.js:7413:22)
    at o (https://cx20.github.io/gltf-test/libs/grimoiregl/grimoirejs-gltf/1.7.1/grimoire-gltf.min.js:1:17395)
```

**Comment by kyasbal-1994** [comment]
Supported by https://github.com/GrimoireGL/grimoirejs-gltf/pull/7
