### ISSUE TITLE
Can not display a glTF model that includes LINES in the Primitive type

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#5]
I tried to display gopher.gltf and I got an error.
http://jsdo.it/cx20/o2xF

```
Uncaught Error: Specified buffer "NORMAL was not found on this geometry while attempt to bind "normal" of attribute variables.

  All of the vertex buffer available on this geometry is TEXCOORD_0,POSITION"
    at Function.bindBufferToAttribute (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:27767:25)
    at Pass.draw (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:27546:38)
    at Technique.draw (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:27436:34)
    at Material.draw (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:27358:29)
    at MeshRenderer.render (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:28466:52)
    at https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:23870:32
    at Array.forEach (native)
    at RenderQueue.renderAll (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:23869:32)
    at CameraComponent.renderScene (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:23617:37)
    at RenderSceneComponent.$render (https://unpkg.com/grimoirejs-preset-basic@1.6.8/register/grimoire-preset-basic.js:29425:27)
```
I think that mesh with primitive type "LINES" probably failed to display.
https://github.com/cx20/gopher-3d/blob/gltf/gopher.gltf
![image](https://cloud.githubusercontent.com/assets/1833979/21747698/524daa58-d5b3-11e6-90bf-596e674a185f.png)

**Comment by kyasbal-1994** [comment]
Sure!

**Comment by cx20** [comment]
I confirmed that it has been fixed in the latest version.
http://jsdo.it/cx20/o2xF

This Issue can be closed.
